### ISSUE TITLE
Why hasn't v1.0.0 been published to crates.io?

### ISSUE THREAD

**Issue by Folyd** [atroche/rust-headless-chrome#323]
https://github.com/atroche/rust-headless-chrome/releases/tag/v1.0.0 has been released a couple of months, but it is still v0.9 on crates.io.

**Comment by llGaetanll** [comment]
For anyone else facing this problem, you can still use v1 with cargo by setting your dependency to the following:
```toml
[dependencies]
headless_chrome = { git = "https://github.com/atroche/rust-headless-chrome", rev = "fd9ba91" }
```
Where `fd9ba91` is the commit hash for v1
