### ISSUE TITLE
Change error API from `failure` as it's deprecated

### ISSUE THREAD

**Issue by Zerowalker** [atroche/rust-headless-chrome#330]
`failure` is deprecated so it might be a good idea to change to one of it's successors.

here's what it says on the repository:

> Notice: failure is deprecated. If you liked failure's API, consider using:
> 
> [Anyhow](https://github.com/dtolnay/anyhow) is a good replacement for failure::Error.
> [thiserror](https://github.com/dtolnay/thiserror) is a good, near drop-in replacement for #[derive(Fail)].

I have personally mostly used `thiserror` so I might be able to try and do a conversion if that one is wanted.
I will gladly try the other as well though if that's the case as I'm bringing it up:)

Thanks for all the work into this project:)!

**Comment by mbergkvist** [comment]
Release [v1.0.0](https://github.com/atroche/rust-headless-chrome/releases/tag/v1.0.0) replaces error handling with anyhow. Unfortunately this release is not available on [crates.io](https://crates.io/), but you can change your dependency to the commit tagged by v1.0.0

```toml
[dependencies.headless_chrome]
features = ["fetch"]
git = "https://github.com/atroche/rust-headless-chrome"
rev = "fd9ba91"
```
